# Generated by Django 4.1 on 2022-08-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cor_marca_carro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='site',
        ),
        migrations.AddField(
            model_name='carro',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carro',
            name='preco',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cor',
            name='nome',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
